spring.application.name=SmartRoute

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/smartroute?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=alunoinfo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Gemini API
gemini.api.key=AIzaSyB8cui8YlCBAa5uV1U4Q92LEREeBrCBWko

# Logging
logging.level.com.smartroute=INFO
logging.level.org.hibernate.SQL=DEBUG

spring.devtools.livereload.enabled=true